#Boss name gen by Car

import random

name_pt_1 = [
    "Necro",
    "Shadow",
    "Dark",
    "Clever",
    "Ember",
    "Hell",
    "Viral",
    "Broody",
    "Mordrid",
    "Morbid",
    "Blaze",
    "Black",
    "Ember",
    "Frost",
    "Slash",
    "Charm",
    "Rule",
    "Snow",
    "Sneak",
    "Brain",
    "Sly",
    "Bash",
    "Smash",
    "Blast",
    "War",
    "Fury",
    "Shroud",
    "Gold",
    "Warp",
    "Crystal",
    "Chain",
    "Bane",
    "Bolt",
    "Bone",
    "Flesh",
    "Gore",
    "Meta",
    "Soul",
    "Venom",
    "Lure",
    "Steel",
    "Fear",
    "Murder",
    "Kill"
    ]

name_pt_2 = [
    "mancer"
    "lust",
    "lover",
    "slayer",
    "blast",
    "rage",
    "smasher",
    "mace",
    "club",
    "sword",
    "dagger",
    "bash",
    "fang",
    "claw",
    "tooth",
    "beast",
    "mane",
    "chill",
    "shiver",
    "frigid",
    "stealth",
    "craft",
    "snare",
    "shredder",
    "slash",
    "burn",
    "fiend",
    "fright",
    "scare",
    "spawn",
    "brood",
    "blood",
    "seeker",
    "hunter",
    "tracker",
    "greed",
    "miser",
    "vault",
    "spectre",
    "spirit",
    "haunt",
    "soul",
    "edge",
    "blade",
    "fire",
    "burn",
    "flare",
    "cinder",
    "block",
    "brick",
    "blaze",
    "maw",
    "gut",
    "wretch",
    "mouth",
    "thirst",
    "hunger",
    "ender",
    "revenant",
    "relic",
    "master",
    "seeker",
    "brick",
    "cobble",
    "stone",
    "gate",
    "flood",
    "devourer",
    "breath",
    "token",
    "coin",
    "cutter",
    "raiser",
    "hood",
    "cloak",
    "black",
    "devil",
    "kin",
    "demon",
    "hawk",
    "snap",
    "frost",
    "chill",
    "slash"
    ]

descriptor = [
    "crafty",
    "unholy",
    "putrid",
    "unjust",
    "rotten",
    "immoral",
    "sinful",
    "baneful",
    "baleful",
    "beastly",
    "damned",
    "damnable",
    "depraved",
    "calamitous",
    "foul",
    "improper",
    "impolite",
    "malefactor",
    "maleficent",
    "repulsive",
    "offensive",
    "poisonous",
    "bringer of sorrows",
    "bringer of strife",
    "very sad",
    "villainous",
    "vicious",
    "wrathful",
    "nefarious",
    "no good",
    "not very nice",
    "obscene",
    "crime against god",
    "crime against nature",
    "stinky",
    "spiteful",
    "vengeful",
    "hideous",
    "low",
    "loathsome",
    "destructive",
    "waster of souls",
    "ender of lives",
    "deadly",
    "butcher",
    "murderous",
    "lecherous",
    "oppressor",
    "barbarous",
    "cannibal",
    "bloody",
    "destroyer",
    "unholy terror",
    "blight against the gods",
    "bludgeoner",
    "bully",
    "hooligan",
    "mugger",
    "bloodsucker",
    "tyranous",
    "ruffian",
    "tyrant",
    "furious",
    "mischief maker",
    "evil doer",
    "unpleasant",
    "lowly",
    "revolting",
    "malicious",
    "vile",
    "wicked",
    "harm doer",
    "harmful",
    "savage",
    "base",
    "untamed",
    "wild",
    "reprehensible",
    "unprincipled",
    "lewd",
    "indecent",
    "infamous",
    "murderer",
    "tormented",
    "tormentor",
    "ferocious",
    "impure",
    "degenerate",
    "heinous",
    "fiendish",
    "depraved",
    "diabolical",
    "abhorrent",
    "atrocious",
    "bad",
    "perverse",
    "cruel",
    "fiendish",
    "infernal",
    "satanic",
    "serpentine",
    "demonic",
    "bloodhungry",
    "bloodthirsty",
    "brutish",
    "callous",
    "bestial",
    "bitter",
    "hardened",
    "hard-hearted",
    "harsh",
    "fierce",
    "heartless",
    "hateful",
    "monstrous",
    "rancorous",
    "sadistic",
    "relentless",
    "tyrannical",
    "unfeeling",
    "unrelenting",
    "implacable",
    "unkind",
    "inconsiderate",
    "shameless",
    "uncontrollable",
    "corrupt",
    "debauched",
    "rake",
    "unscupulous",
    "unethical",
    "two-faced",
    "cheater",
    "ditry dealer",
    "shady",
    "ruffian",
    "unfair",
    "sneaky",
    "double-crosser",
    "crooked",
    "crook",
    "criminal",
    "felon",
    "slippery",
    "underhanded",
    "cancerous",
    "fatal",
    "destructive",
    "diseased",
    "dangerous",
    "cannibalistic",
    "grim",
    "reaper",
    "violent",
    "mortiferous",
    "venomous",
    "homicidal",
    "dominator",
    "godlike",
    "injurious",
    "mostly harmless",
    "displeasing",
    "disgusting",
    "wretched",
    "nasty",
    "revolting",
    "despicable",
    "detestable",
    "cremator",
    "dissector",
    "slasher",
    "manipulator"
    ]

def boss_name_generator():
    ptone = random.choice (name_pt_1)
    pttwo = random.choice (name_pt_2)
    ptthree = random.choice (descriptor)
    string = ('%s%s the %s' % (ptone, pttwo, ptthree))
    print (string)

def test_1():
    word = random.choice(descriptors)
    print(word)

def test_2():
    boss_name_generator()

if __name__ == "__main__":
    test_2()
